import './globals.css';
import { Inter, Noto_Sans_TC } from 'next/font/google';

const noto_sans = Noto_Sans_TC({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Stylish',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${noto_sans.className} text-custom-grey`}>
        {children}
      </body>
    </html>
  );
}
